# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoCmp < Formula
  desc "Run some compare operations on MongoDB"
  homepage "https://github.com/fadyat/mongo-cmp"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Darwin_x86_64.tar.gz"
      sha256 "5501fc00a47dfd8650e4d3692b803585f6524507bdd9ff2a67b4a6874ebb9eda"

      def install
        bin.install "mongo-cmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Darwin_arm64.tar.gz"
      sha256 "89886cea9e515ed9a387fb19d7ea956ccb5efb63f465ffc4be34b33abc705320"

      def install
        bin.install "mongo-cmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Linux_arm64.tar.gz"
      sha256 "9daabd52566b31811faad733216e24256d881722b74a2802f81d36eec37393d2"

      def install
        bin.install "mongo-cmp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Linux_x86_64.tar.gz"
      sha256 "1c8f7f2b12febec4078819a0e0041a11586d168d8def254ad3f928a3c913121a"

      def install
        bin.install "mongo-cmp"
      end
    end
  end
end
