# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoCmp < Formula
  desc "Run some compare operations on MongoDB"
  homepage "https://github.com/fadyat/mongo-cmp"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Darwin_x86_64.tar.gz"
      sha256 "e0ff6cb5e330fe7189188e1ec89c7cfa5058c3b5a5364da41df079ebf9b73f60"

      def install
        bin.install "mongo-cmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Darwin_arm64.tar.gz"
      sha256 "ffd96e08318e443012a47a7e57173f07e4dc15a3a3dfee72318165af4a383871"

      def install
        bin.install "mongo-cmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Linux_arm64.tar.gz"
      sha256 "32737cc42ec8073a7fc95d71dcde08a6b78fb1869858a89bf8b866df3b2f7d50"

      def install
        bin.install "mongo-cmp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/mongo-cmp/releases/download/v0.0.1/mongo-cmp_Linux_x86_64.tar.gz"
      sha256 "7eb92e8c2938c0db370c8606dc480ae6a14d1aa8396503ca75b6b2c5226257f5"

      def install
        bin.install "mongo-cmp"
      end
    end
  end
end
