# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pump < Formula
  desc "A little randomness for choosing tasks in your world"
  homepage "https://github.com/fadyat/pump"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.3.1/pump_Darwin_x86_64.tar.gz"
      sha256 "c7ad2a5369770360157bf06c548d36b9895b50cebf0bb226fdd671da42eb36f4"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fadyat/pump/releases/download/v0.3.1/pump_Darwin_arm64.tar.gz"
      sha256 "9dfd2525c961c984ffe812f590f5b159db7fd9af5aa9d50ffed6d36b1ce68473"

      def install
        bin.install "pump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.3.1/pump_Linux_x86_64.tar.gz"
      sha256 "e6315f623bd1e01b7ac67252906c634b756369d3da68b77fead57911f66b5bb6"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fadyat/pump/releases/download/v0.3.1/pump_Linux_arm64.tar.gz"
      sha256 "f010ea10a87803c23f338c2eae755d9c0a99679105e58764e0d0daf13f191542"

      def install
        bin.install "pump"
      end
    end
  end
end
