# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pump < Formula
  desc "A little randomness for choosing tasks in your world"
  homepage "https://github.com/fadyat/pump"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fadyat/pump/releases/download/v0.4.0/pump_Darwin_arm64.tar.gz"
      sha256 "90c9bd4028e9887c3467d1c386d406ea2409aa712d708342f1c33200d30ef15f"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.4.0/pump_Darwin_x86_64.tar.gz"
      sha256 "03acd7fd2d8cde0e81e6b49651a7a2c32b53484226abfdb828651ef5081eb220"

      def install
        bin.install "pump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fadyat/pump/releases/download/v0.4.0/pump_Linux_arm64.tar.gz"
      sha256 "faa11fceb36d8b6dd2139b6e3701c7677288e42a255982ab51b310e9912bf994"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.4.0/pump_Linux_x86_64.tar.gz"
      sha256 "af73d221a3c8c27374dec53cbba54bdb8602f57b00af519bfb9a21d82251e466"

      def install
        bin.install "pump"
      end
    end
  end
end
