# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pump < Formula
  desc "A little randomness for choosing tasks in your world"
  homepage "https://github.com/fadyat/pump"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.0.1/pump_Darwin_x86_64.tar.gz"
      sha256 "05384a0f71c5163465ee817e3ada8c333e14e1252f717df19963017829b314a9"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fadyat/pump/releases/download/v0.0.1/pump_Darwin_arm64.tar.gz"
      sha256 "b1135248def1f22d0b5573096372f11502b8c1495ccaaff2379a4d3e23ee1871"

      def install
        bin.install "pump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fadyat/pump/releases/download/v0.0.1/pump_Linux_arm64.tar.gz"
      sha256 "0a2d4f1c96c196fe21041f47aaeb5fe72fb2e85c2750994a165cad6de79ced8c"

      def install
        bin.install "pump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fadyat/pump/releases/download/v0.0.1/pump_Linux_x86_64.tar.gz"
      sha256 "cb44f92eb1dacbe2f2cf4c9230713ea2e4826f3451f386ef0af4ce8b00ddfaa9"

      def install
        bin.install "pump"
      end
    end
  end
end
